name: studtime
description: A new Flutter project.

<<<<<<< Updated upstream
publish_to: "none" # Remove this line if you wish to publish to pub.dev
=======
publish_to: "none"
>>>>>>> Stashed changes

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
  cupertino_icons: ^1.0.2
  gradient_text: ^1.0.2
  go_router: ^6.0.1
  flutter_hooks: ^0.18.5+1
  time: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< Updated upstream
=======
  build_runner: ^2.3.2
>>>>>>> Stashed changes
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.1.0+1

<<<<<<< Updated upstream
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  web:
    generate: true
    image_path: "assets/ic_launcher.png"

=======
>>>>>>> Stashed changes
flutter:
  uses-material-design: true
  assets:
    - assets/intro/

<<<<<<< Updated upstream
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
=======
flutter_gen:
  output: lib/resources/assets
  line_length: 80
  integrations:
    flutter_svg: true
>>>>>>> Stashed changes
