name: studtime
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gradient_text: ^1.0.2
  go_router: ^6.0.1
  flutter_hooks: ^0.18.5+1
  time: ^2.1.3
  flutter_bloc: ^8.1.1
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0

flutter_gen:
  output: lib/resources/assets
  line_length: 80
  integrations:
    flutter_svg: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  web:
    generate: true
    image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/intro/
