name: studtime
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gradient_text: ^1.0.2
  flutter_hooks: ^0.18.5+1
  time: ^2.1.3
  flutter_bloc: ^8.1.1
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  shared_preferences: ^2.0.17
  freezed_annotation: ^2.2.0
  cloud_firestore: ^4.3.1
  json_annotation: ^4.8.0
  introduction_screen: ^3.1.4
  flutter_svg: ^1.1.6
  flutter_easyloading: ^3.0.5
  titled_navigation_bar: ^5.0.0-nullsafety.0
  flutter_intro: ^3.0.2
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  intl: ^0.18.0
  flutter_keyboard_size: ^1.0.1
  flutter_swipe_action_cell: ^3.1.0
  image_picker: ^0.8.6+1
  path_provider: ^2.0.12
  share_plus: ^6.3.1
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  freezed: ^2.3.2
  json_serializable: ^6.6.0

flutter_gen:
  output: lib/src/shared/assets
  line_length: 80
  integrations:
    flutter_svg: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  web:
    generate: true
    image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/ic_launcher.png
    - assets/intro/
    - assets/setup/
    - assets/shared/
    - assets/about/
