// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR__BeQT1pyS3NHFle5hfefw5CBBknb6A',
    appId: '1:396986104003:web:598fa83c8ec5c471918a76',
    messagingSenderId: '396986104003',
    projectId: 'studtime-e721c',
    authDomain: 'studtime-e721c.firebaseapp.com',
    storageBucket: 'studtime-e721c.appspot.com',
    measurementId: 'G-9GEQ00D2L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2e2Wv-f1gwOUeDpxK1SZeHStKDXYNhBo',
    appId: '1:396986104003:android:e6104724f744b4bb918a76',
    messagingSenderId: '396986104003',
    projectId: 'studtime-e721c',
    storageBucket: 'studtime-e721c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWKijtJPp6wIQwwgoR6UOu5BL4GooLaEc',
    appId: '1:396986104003:ios:6f37579246f4e311918a76',
    messagingSenderId: '396986104003',
    projectId: 'studtime-e721c',
    storageBucket: 'studtime-e721c.appspot.com',
    iosClientId: '396986104003-crm55ol5f4guto7boqd5c87kckolcis2.apps.googleusercontent.com',
    iosBundleId: 'com.example.studtime',
  );
}
